# Generated by Django 3.0 on 2021-07-21 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tnp_admin', '0002_auto_20210302_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_type',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
