# Generated by Django 3.0 on 2021-07-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnp_admin', '0003_admin_admin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_type',
        ),
    ]
