# Generated by Django 3.0 on 2021-07-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnp_admin', '0004_remove_admin_admin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
