# Generated by Django 3.0 on 2022-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnp_admin', '0005_admin_admin_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='mailResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100)),
                ('stud_user', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=200)),
                ('stud_response', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
