# Generated by Django 3.0 on 2022-08-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnp_admin', '0007_auto_20220812_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ctc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
