# Generated by Django 3.0 on 2022-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnp_admin', '0008_auto_20220812_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='required_any_live_kt',
            field=models.IntegerField(default=0),
        ),
    ]
