# Generated by Django 3.0 on 2021-07-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_user_admin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_type',
        ),
    ]
