# Generated by Django 3.0 on 2022-06-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20220625_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='oneto6',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
