# Generated by Django 3.0 on 2022-08-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20220803_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='any_present_kt',
            field=models.IntegerField(default=0, max_length=111),
        ),
    ]
