# Generated by Django 3.0 on 2022-08-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_resume_any_present_kt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='any_present_kt',
            field=models.IntegerField(default=0),
        ),
    ]
